apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: copy-fail-destroyer
  namespace: copy-fail-destroyer
  labels:
    app: copy-fail-destroyer
spec:
  selector:
    matchLabels:
      app: copy-fail-destroyer
  template:
    metadata:
      labels:
        app: copy-fail-destroyer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: destroyer
          image: ghcr.io/norskhelsenett/copy-fail-destroyer:0.1.4
          ports:
            - containerPort: 9100
              name: metrics
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
